//! Lightning: a midpoint-displacement bolt used as a ~0.15s failure flash.
//!
//! The bolt is a vertical polyline from top-center to a bottom x, generated by recursively
//! displacing midpoints with decreasing jitter (from an embedded [`SplitMix64`]). Every point
//! is clamped into `[0, w) × [0, h)` so the path is always renderable. The engine holds a
//! countdown timer; while `> 0` the bolt renders and the timer decrements by `dt`.

use super::SplitMix64;

/// Flash duration in seconds (~0.15s).
pub const FLASH_SECS: f32 = 0.15;

/// Default bolt bounds for generation (cells).
pub const BOLT_W: usize = 48;
pub const BOLT_H: usize = 18;

/// The lightning effect state.
#[derive(Debug, Clone)]
pub struct Lightning {
    /// Remaining flash time in seconds (0 = inactive).
    timer: f32,
    /// The current bolt polyline (cell coordinates), regenerated on each flash.
    path: Vec<(u16, u16)>,
    rng: SplitMix64,
    w: usize,
    h: usize,
}

impl Lightning {
    pub fn new(seed: u64) -> Self {
        Self { timer: 0.0, path: Vec::new(), rng: SplitMix64::new(seed), w: BOLT_W, h: BOLT_H }
    }

    /// Whether the flash is currently visible.
    pub fn active(&self) -> bool {
        self.timer > 0.0
    }

    /// Remaining flash time (seconds). (Introspection / tests.)
    #[allow(dead_code)]
    pub fn timer(&self) -> f32 {
        self.timer
    }

    /// The current bolt polyline.
    pub fn path(&self) -> &[(u16, u16)] {
        &self.path
    }

    /// Trigger a flash using the default bounds.
    pub fn flash(&mut self) {
        self.flash_with(self.w, self.h);
    }

    /// Trigger a flash, regenerating the bolt for `(w, h)` bounds.
    pub fn flash_with(&mut self, w: usize, h: usize) {
        self.w = w.max(1);
        self.h = h.max(2);
        self.timer = FLASH_SECS;
        self.path = self.generate();
    }

    /// Cancel any in-flight flash.
    pub fn cancel(&mut self) {
        self.timer = 0.0;
        self.path.clear();
    }

    /// Decrement the flash timer by `dt`. Pure (no clock, no RNG).
    pub fn step(&mut self, dt: f32) {
        if self.timer > 0.0 {
            self.timer = (self.timer - dt).max(0.0);
        }
    }

    /// Generate a midpoint-displacement bolt from top-center to a random bottom x.
    /// Every produced point is clamped into bounds.
    fn generate(&mut self) -> Vec<(u16, u16)> {
        let w = self.w as f32;
        let h = self.h as f32;
        let start = (w * 0.5, 0.0_f32);
        // Bottom end wanders within the central band.
        let end_x = w * (0.25 + self.rng.next_f32() * 0.5);
        let end = (end_x, h - 1.0);

        // Build a list of x-offsets via midpoint displacement on a fixed number of segments.
        let mut points: Vec<(f32, f32)> = vec![start, end];
        let levels = 5; // 2^5 + 1 = 33 points max — bounded.
        let mut jitter = w * 0.25;
        for _ in 0..levels {
            let mut next: Vec<(f32, f32)> = Vec::with_capacity(points.len() * 2);
            for i in 0..points.len() - 1 {
                let a = points[i];
                let b = points[i + 1];
                next.push(a);
                let mx = (a.0 + b.0) * 0.5;
                let my = (a.1 + b.1) * 0.5;
                let disp = (self.rng.next_f32() - 0.5) * 2.0 * jitter;
                next.push((mx + disp, my));
            }
            next.push(*points.last().unwrap());
            points = next;
            jitter *= 0.5;
        }

        // Clamp every point into bounds and quantise to cells.
        points
            .into_iter()
            .map(|(x, y)| {
                let xi = x.clamp(0.0, w - 1.0).round() as u16;
                let yi = y.clamp(0.0, h - 1.0).round() as u16;
                (xi, yi)
            })
            .collect()
    }

    /// Pick a diagonal/vertical glyph for the segment leaving point `i` (for rendering).
    pub fn glyph_at(&self, i: usize) -> char {
        if self.path.len() < 2 || i + 1 >= self.path.len() {
            return '│';
        }
        let (x0, _) = self.path[i];
        let (x1, _) = self.path[i + 1];
        match x1.cmp(&x0) {
            std::cmp::Ordering::Less => '╱',
            std::cmp::Ordering::Greater => '╲',
            std::cmp::Ordering::Equal => '│',
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lightning_path_in_bounds() {
        let mut l = Lightning::new(0x11);
        // Try several bounds, including tiny ones.
        for &(w, h) in &[(48usize, 18usize), (10, 4), (2, 2), (120, 40)] {
            l.flash_with(w, h);
            assert!(!l.path().is_empty());
            for &(x, y) in l.path() {
                assert!((x as usize) < w, "x {} >= w {}", x, w);
                assert!((y as usize) < h, "y {} >= h {}", y, h);
            }
        }
    }

    #[test]
    fn lightning_flash_expires_after_duration() {
        let mut l = Lightning::new(0x11);
        l.flash();
        assert!(l.active());
        // 0.15s flash; step 0.05 four times ⇒ inactive.
        l.step(0.05);
        l.step(0.05);
        l.step(0.05);
        l.step(0.05);
        assert!(!l.active());
    }

    #[test]
    fn lightning_starts_top_center_ish() {
        let mut l = Lightning::new(0x99);
        l.flash_with(40, 10);
        let (x0, y0) = l.path()[0];
        assert_eq!(y0, 0, "bolt starts at the top row");
        // start near center
        assert!((x0 as i32 - 20).abs() <= 1);
    }

    #[test]
    fn lightning_deterministic() {
        let mut a = Lightning::new(0x7);
        let mut b = Lightning::new(0x7);
        a.flash_with(50, 20);
        b.flash_with(50, 20);
        assert_eq!(a.path(), b.path());
    }
}
